-- sqlite3 .flaskr.db < schema.sql
-- drop table if exists entries;
-- create table entries (
-- 	id integer primary key autoincrement,
-- 	title text not null,
-- 	text text not null
-- );

-- drop table if exists users;
-- create table users (
-- 	username nvarchar(15) primary key,
-- 	password nvarchar(20) not null
-- );